import { Curriculum } from '../types';

export const curriculum: Curriculum = {
  '6': {
    'Science': [
      'Food: Where Does It Come From?',
      'Components of Food',
      'Fibre to Fabric',
      'Sorting Materials Into Groups',
      'Separation of Substances',
      'Changes Around Us',
      'Getting to Know Plants',
      'Body Movements',
      'The Living Organisms and Their Surroundings',
      'Motion and Measurement of Distances',
      'Light, Shadows and Reflections',
      'Electricity and Circuits',
      'Fun with Magnets',
      'Water',
      'Air Around Us',
      'Garbage In, Garbage Out'
    ],
    'Maths': [
      'Knowing Our Numbers',
      'Whole Numbers',
      'Playing with Numbers',
      'Basic Geometrical Ideas',
      'Understanding Elementary Shapes',
      'Integers',
      'Fractions',
      'Decimals',
      'Data Handling',
      'Mensuration',
      'Algebra',
      'Ratio and Proportion',
      'Symmetry',
      'Practical Geometry'
    ],
    'Social Studies': [
      'What, Where, How and When?',
      'On The Trail of the Earliest People',
      'From Gathering to Growing Food',
      'In the Earliest Cities',
      'What Books and Burials Tell Us',
      'Kingdoms, Kings and an Early Republic',
      'New Questions and Ideas',
      'Ashoka, The Emperor Who Gave Up War',
      'Vital Villages, Thriving Towns',
      'Traders, Kings and Pilgrims',
      'New Empires and Kingdoms',
      'Buildings, Paintings and Books',
      'Understanding Diversity',
      'Diversity and Discrimination',
      'What is Government?',
      'Key Elements of a Democratic Government',
      'Panchayati Raj',
      'Rural Administration',
      'Urban Administration',
      'Rural Livelihoods',
      'Urban Livelihoods',
      'The Earth in the Solar System',
      'Globe: Latitudes and Longitudes',
      'Motions of the Earth',
      'Maps',
      'Major Domains of the Earth',
      'Major Landforms of the Earth',
      'Our Country - India',
      'India: Climate, Vegetation and Wildlife'
    ],
  },
  '7': {
    'Science': [
      'Nutrition in Plants',
      'Nutrition in Animals',
      'Fibre to Fabric',
      'Heat',
      'Acids, Bases and Salts',
      'Physical and Chemical Changes',
      'Weather, Climate and Adaptations of Animals to Climate',
      'Winds, Storms and Cyclones',
      'Soil',
      'Respiration in Organisms',
      'Transportation in Animals and Plants',
      'Reproduction in Plants',
      'Motion and Time',
      'Electric Current and its Effects',
      'Light',
      'Water: A Precious Resource',
      'Forests: Our Lifeline',
      'Wastewater Story'
    ],
    'Maths': [
      'Integers',
      'Fractions and Decimals',
      'Data Handling',
      'Simple Equations',
      'Lines and Angles',
      'The Triangle and its Properties',
      'Congruence of Triangles',
      'Comparing Quantities',
      'Rational Numbers',
      'Practical Geometry',
      'Perimeter and Area',
      'Algebraic Expressions',
      'Exponents and Powers',
      'Symmetry',
      'Visualising Solid Shapes'
    ],
    'Social Studies': [
      'Tracing Changes Through A Thousand Years',
      'New Kings And Kingdoms',
      'The Delhi Sultans',
      'The Mughal Empire',
      'Rulers and Buildings',
      'Towns, Traders and Craftspersons',
      'Tribes, Nomads and Settled Communities',
      'Devotional Paths to the Divine',
      'The Making of Regional Cultures',
      'Eighteenth-Century Political Formations',
      'On Equality',
      'Role of the Government in Health',
      'How the State Government Works',
      'Growing Up as Boys and Girls',
      'Women Change the World',
      'Understanding Media',
      'Markets Around Us',
      'A Shirt in the Market',
      'Environment',
      'Inside Our Earth',
      'Our Changing Earth',
      'Air',
      'Water',
      'Natural Vegetation and Wildlife',
      'Human Environment - Settlement, Transport and Communication'
    ],
  },
  '8': {
    'Science': [
      'Crop Production and Management',
      'Microorganisms: Friend and Foe',
      'Synthetic Fibres and Plastics',
      'Materials: Metals and Non-Metals',
      'Coal and Petroleum',
      'Combustion and Flame',
      'Conservation of Plants and Animals',
      'Cell - Structure and Functions',
      'Reproduction in Animals',
      'Reaching the Age of Adolescence',
      'Force and Pressure',
      'Friction',
      'Sound',
      'Chemical Effects of Electric Current',
      'Some Natural Phenomena',
      'Light',
      'Stars and The Solar System',
      'Pollution of Air and Water'
    ],
    'Maths': [
      'Rational Numbers',
      'Linear Equations in One Variable',
      'Understanding Quadrilaterals',
      'Practical Geometry',
      'Data Handling',
      'Squares and Square Roots',
      'Cubes and Cube Roots',
      'Comparing Quantities',
      'Algebraic Expressions and Identities',
      'Visualising Solid Shapes',
      'Mensuration',
      'Exponents and Powers',
      'Direct and Inverse Proportions',
      'Factorisation',
      'Introduction to Graphs'
    ],
    'Social Studies': [
      'How, When and Where',
      'From Trade to Territory',
      'Ruling the Countryside',
      'Tribals, Dikus and the Vision of a Golden Age',
      'When People Rebel',
      'Colonialism and the City',
      'Weavers, Iron Smelters and Factory Owners',
      'Civilising the "Native", Educating the Nation',
      'Women, Caste and Reform',
      'The Making of the National Movement: 1870s-1947',
      'India After Independence',
      'The Indian Constitution',
      'Understanding Secularism',
      'Why Do We Need a Parliament?',
      'Understanding Laws',
      'Judiciary',
      'Understanding Our Criminal Justice System',
      'Understanding Marginalisation',
      'Confronting Marginalisation',
      'Public Facilities',
      'Law and Social Justice',
      'Resources',
      'Land, Soil, Water, Natural Vegetation and Wildlife Resources',
      'Mineral and Power Resources',
      'Agriculture',
      'Industries',
      'Human Resources'
    ],
  },
  '9': {
    'Science': [
      'Matter in Our Surroundings',
      'Is Matter Around Us Pure?',
      'Atoms and Molecules',
      'Structure of the Atom',
      'The Fundamental Unit of Life',
      'Tissues',
      'Diversity in Living Organisms',
      'Motion',
      'Force and Laws of Motion',
      'Gravitation',
      'Work and Energy',
      'Sound',
      'Why Do We Fall Ill?',
      'Natural Resources',
      'Improvement in Food Resources'
    ],
    'Maths': [
      'Number Systems',
      'Polynomials',
      'Coordinate Geometry',
      'Linear Equations in Two Variables',
      'Introduction to Euclid\'s Geometry',
      'Lines and Angles',
      'Triangles',
      'Quadrilaterals',
      'Areas of Parallelograms and Triangles',
      'Circles',
      'Constructions',
      'Heron\'s Formula',
      'Surface Areas and Volumes',
      'Statistics',
      'Probability'
    ],
    'Social Studies': [
      'The French Revolution',
      'Socialism in Europe and the Russian Revolution',
      'Nazism and the Rise of Hitler',
      'Forest Society and Colonialism',
      'Pastoralists in the Modern World',
      'India - Size and Location',
      'Physical Features of India',
      'Drainage',
      'Climate',
      'Natural Vegetation and Wild Life',
      'Population',
      'What is Democracy? Why Democracy?',
      'Constitutional Design',
      'Electoral Politics',
      'Working of Institutions',
      'Democratic Rights',
      'The Story of Village Palampur',
      'People as Resource',
      'Poverty as a Challenge',
      'Food Security in India'
    ],
  },
  '10': {
    'Science': [
      'Chemical Reactions and Equations',
      'Acids, Bases and Salts',
      'Metals and Non-metals',
      'Carbon and its Compounds',
      'Life Processes',
      'Control and Coordination',
      'How do Organisms Reproduce?',
      'Heredity',
      'Light - Reflection and Refraction',
      'Human Eye and Colourful World',
      'Electricity',
      'Magnetic Effects of Electric Current',
      'Our Environment'
    ],
    'Maths': [
      'Real Numbers',
      'Polynomials',
      'Pair of Linear Equations in Two Variables',
      'Quadratic Equations',
      'Arithmetic Progressions',
      'Triangles',
      'Coordinate Geometry',
      'Introduction to Trigonometry',
      'Some Applications of Trigonometry',
      'Circles',
      'Constructions',
      'Areas Related to Circles',
      'Surface Areas and Volumes',
      'Statistics',
      'Probability'
    ],
    'Social Studies': [
      'The Rise of Nationalism in Europe',
      'Nationalism in India',
      'The Making of a Global World',
      'The Age of Industrialisation',
      'Print Culture and the Modern World',
      'Resources and Development',
      'Forest and Wildlife Resources',
      'Water Resources',
      'Agriculture',
      'Minerals and Energy Resources',
      'Manufacturing Industries',
      'Lifelines of National Economy',
      'Power Sharing',
      'Federalism',
      'Democracy and Diversity',
      'Gender, Religion and Caste',
      'Political Parties',
      'Outcomes of Democracy',
      'Development',
      'Sectors of the Indian Economy',
      'Money and Credit',
      'Globalisation and the Indian Economy',
      'Consumer Rights'
    ]
  },
  '11': {
    'Physics': [
      'Units and Measurements',
      'Motion in a Straight Line',
      'Motion in a Plane',
      'Laws of Motion',
      'Work, Energy and Power',
      'System of Particles and Rotational Motion',
      'Gravitation',
      'Mechanical Properties of Solids',
      'Mechanical Properties of Fluids',
      'Thermal Properties of Matter',
      'Thermodynamics',
      'Kinetic Theory',
      'Oscillations',
      'Waves'
    ],
    'Chemistry': [
      'Some Basic Concepts of Chemistry',
      'Structure of Atom',
      'Classification of Elements and Periodicity in Properties',
      'Chemical Bonding and Molecular Structure',
      'States of Matter',
      'Thermodynamics',
      'Equilibrium',
      'Redox Reactions',
      'Hydrogen',
      'The s-Block Elements',
      'The p-Block Elements (Group 13 & 14)',
      'Organic Chemistry – Some Basic Principles and Techniques',
      'Hydrocarbons'
    ],
    'Biology': [
      'The Living World',
      'Biological Classification',
      'Plant Kingdom',
      'Animal Kingdom',
      'Morphology of Flowering Plants',
      'Anatomy of Flowering Plants',
      'Structural Organisation in Animals',
      'Cell: The Unit of Life',
      'Biomolecules',
      'Cell Cycle and Cell Division',
      'Transport in Plants',
      'Mineral Nutrition',
      'Photosynthesis in Higher Plants',
      'Respiration in Plants',
      'Plant Growth and Development',
      'Digestion and Absorption',
      'Breathing and Exchange of Gases',
      'Body Fluids and Circulation',
      'Excretory Products and their Elimination',
      'Locomotion and Movement',
      'Neural Control and Coordination',
      'Chemical Coordination and Integration'
    ],
    'Maths': [
      'Sets',
      'Relations and Functions',
      'Trigonometric Functions',
      'Principle of Mathematical Induction',
      'Complex Numbers and Quadratic Equations',
      'Linear Inequalities',
      'Permutations and Combinations',
      'Binomial Theorem',
      'Sequences and Series',
      'Straight Lines',
      'Conic Sections',
      'Introduction to Three Dimensional Geometry',
      'Limits and Derivatives',
      'Mathematical Reasoning',
      'Statistics',
      'Probability'
    ]
  },
  '12': {
    'Physics': [
      'Electric Charges and Fields',
      'Electrostatic Potential and Capacitance',
      'Current Electricity',
      'Moving Charges and Magnetism',
      'Magnetism and Matter',
      'Electromagnetic Induction',
      'Alternating Current',
      'Electromagnetic Waves',
      'Ray Optics and Optical Instruments',
      'Wave Optics',
      'Dual Nature of Radiation and Matter',
      'Atoms',
      'Nuclei',
      'Semiconductor Electronics: Materials, Devices and Simple Circuits'
    ],
    'Chemistry': [
      'The Solid State',
      'Solutions',
      'Electrochemistry',
      'Chemical Kinetics',
      'Surface Chemistry',
      'General Principles and Processes of Isolation of Elements',
      'The p-Block Elements (Group 15, 16, 17, 18)',
      'The d- and f-Block Elements',
      'Coordination Compounds',
      'Haloalkanes and Haloarenes',
      'Alcohols, Phenols and Ethers',
      'Aldehydes, Ketones and Carboxylic Acids',
      'Amines',
      'Biomolecules',
      'Polymers',
      'Chemistry in Everyday Life'
    ],
    'Biology': [
      'Reproduction in Organisms',
      'Sexual Reproduction in Flowering Plants',
      'Human Reproduction',
      'Reproductive Health',
      'Principles of Inheritance and Variation',
      'Molecular Basis of Inheritance',
      'Evolution',
      'Human Health and Disease',
      'Strategies for Enhancement in Food Production',
      'Microbes in Human Welfare',
      'Biotechnology: Principles and Processes',
      'Biotechnology and its Applications',
      'Organisms and Populations',
      'Ecosystem',
      'Biodiversity and Conservation',
      'Environmental Issues'
    ],
    'Maths': [
      'Relations and Functions',
      'Inverse Trigonometric Functions',
      'Matrices',
      'Determinants',
      'Continuity and Differentiability',
      'Application of Derivatives',
      'Integrals',
      'Application of Integrals',
      'Differential Equations',
      'Vector Algebra',
      'Three Dimensional Geometry',
      'Linear Programming',
      'Probability'
    ]
  }
};
